# NumPy Initialization

In [1]:
#numpy - python package for numerical computing
import numpy

In [2]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [3]:
from numpy import *

In [4]:
array([1, 2, 3])

array([1, 2, 3])

In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.__version__

'1.18.5'

In [7]:
array1 = np.arange(100000)

In [ ]:
np.arange()

In [8]:
array2 = list(range(100000))

In [9]:
%time for i in range(10): my_array1 = array1*2

Wall time: 2.01 ms


In [10]:
%time for i in range(10): my_array2 = [x*2 for x in array2]

Wall time: 55 ms


In [18]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> for
The "for" statement
*******************

The "for" statement is used to iterate over the elements of a sequence
(such as a string, tuple or list) or other iterable object:

   for_stmt ::= "for" target_list "in" expression_list ":" suite
                ["else" ":" suite]

The expression list is evaluated once; it should yield 

In [ ]:
help(np.sort)

In [ ]:
from numpy import doc

In [ ]:
help(doc)

In [17]:
help(np.doc.basics)

Help on module numpy.doc.basics in numpy.doc:

NAME
    numpy.doc.basics

DESCRIPTION
    Array basics
    
    Array types and conversions between types
    
    NumPy supports a much greater variety of numerical types than Python does.
    This section shows which are available, and how to modify an array's data-type.
    
    The primitive types supported are tied closely to those in C:
    
    .. list-table::
        :header-rows: 1
    
        * - Numpy type
          - C type
          - Description
    
        * - `np.bool_`
          - ``bool``
          - Boolean (True or False) stored as a byte
    
        * - `np.byte`
          - ``signed char``
          - Platform-defined
    
        * - `np.ubyte`
          - ``unsigned char``
          - Platform-defined
    
        * - `np.short`
          - ``short``
          - Platform-defined
    
        * - `np.ushort`
          - ``unsigned short``
          - Platform-defined
    
        * - `np.intc`
          - ``int``

In [16]:
np.lookfor('arange')

Search results for 'arange'
---------------------------
numpy.arange
    Return evenly spaced values within a given interval.
numpy.ma.arange
    Return evenly spaced values within a given interval.
numpy.add
    Add arguments element-wise.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.dot
    Dot product of two arrays. Specifically,
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.ix_
    Construct an open mesh from multiple sequences.
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.mod
    Return element-wise remainder of division.
numpy.pad
    Pad an array.
numpy.ptp
    Range of values (maximum - minimum) along an axis.
numpy.put
    Replaces specified elements of an array with given values.
numpy.who
    Print the NumPy arrays in the given dictionary.
numpy.amax
    Return the maximum of an array or maximum along an axis.
numpy.amin
    Return the minimum of an array or minimum along an ax

In [ ]:
np?

In [15]:
np.arange?

In [20]:
np.arange??

In [ ]:
np.arange() 